### ISSUE TITLE
`docs`: Update GHA workflow to fetch and compile the raw `nmdc-runtime` documentation

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/docs#1]
Target delivery date: Before next documentation squad meeting (soonest one AFTER September 19, 2024).

**Comment by ssarrafan** [comment]
This isn't highest priority. Can I move this to the next sprint or backlog @eecavanna ?

**Comment by eecavanna** [comment]
Yes, next sprint, please.

**Comment by eecavanna** [comment]
I filed an issue "upstream" that is related to this task. Issue: https://github.com/microbiomedata/nmdc-runtime/issues/730
