### ISSUE TITLE
meta MS - Yuri

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#17]
Follow the template below for the index.rst file that is in the docs folder of the repo for your workflow:
Title of Workflow
(Image)
Workflow overview
Workflow availability
Requirements for Execution
Hardware requirements
Workflow dependencies
Software
Database(s)
Sample dataset(s)
Input
Output
Version history
Point of contact

If you have updated figures please put the editable components of the figures [here](https://drive.google.com/drive/folders/1MEmTMLMPeDMQaF-LYnpJswjVmn9MUFTX) as well as in the documentation 
Please follow the following format for updating your documentation:

**Comment by ssarrafan** [comment]
@corilo can you please update with a link to the doc draft and status 
I'll move to one more sprint
FYI @aclum

**Comment by ssarrafan** [comment]
@corilo what's the status of this? Is this in progress? Can you complete this documentation by Friday?

**Comment by kaijli** [comment]
added standardized workflow figure https://github.com/microbiomedata/metaMS/pull/62

**Comment by kaijli** [comment]
not sure where to put this, but enviroMS also has PR for figure update https://github.com/microbiomedata/enviroMS/pull/10

**Comment by aclum** [comment]
cc @kheal

**Comment by ssarrafan** [comment]
@corilo said Meta MS documentation is done/updated.  I'm moving to review for @aclum to check.

**Comment by corilo** [comment]
Just added the Hardware Requirements that was missing

**Comment by aclum** [comment]
@corilo can you update the order of the sections so it matches what is in the issue description please. Also please take a look at the PR @kaijli, that version has a slightly different image where the blue box isn't as cut off. Please either accept those changes or close the PR without merging. https://github.com/microbiomedata/enviroMS/pull/10

**Comment by ssarrafan** [comment]
Moving to next sprint to finish review and changes @corilo @aclum @kaijli

**Comment by corilo** [comment]
> @corilo can you update the order of the sections so it matches what is in the issue description please. Also please take a look at the PR @kaijli, that version has a slightly different image where the blue box isn't as cut off. Please either accept those changes or close the PR without merging. [microbiomedata/enviroMS#10](https://github.com/microbiomedata/enviroMS/pull/10)

@aclum I have just added the new images and changed the order of the sections in the documentation. Please let me know if these changes meet your requirements. Thanks.

**Comment by aclum** [comment]
Could you
 1) expand on the database information. A link to more information about the database and what database version is used (see https://github.com/microbiomedata/mg_annotation/blob/master/docs/index.rst as an example)
2) based on recent discussions it would be great to include a few sentences about when to use each of the calibration files in the workflow dependencies section.

**Comment by ssarrafan** [comment]
@corilo can this be closed/wrapped up this week please?  
@aclum

**Comment by corilo** [comment]
Not yet, I still need to work on Alicia asks, will do that next week

**Comment by ssarrafan** [comment]
Moving to next sprint per @corilo comment above.

**Comment by corilo** [comment]
I added more information about the calibration files for the enviroMS workflow and a few sentences about the database used for GC-MS. However, we need an external link or documentation that we can share at this point. The transparency issue will be solved when the API for the Metabolomics Database is made available (https://www.emsl.pnnl.gov/project/60086), which is set to be this month. I'll update the documentation as soon as the API is live.

**Comment by ssarrafan** [comment]
@corilo @aclum can this issue be closed now? Thanks for working on this.
