### ISSUE TITLE
Documentation tasks - DMP Data Management - Parent Issue

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#23]
Add to this list of tasks to review and update DMP related documentation:

- [x]     https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/data_plan.html 
- [x] https://microbiomedata.org/data-management/
- [ ]

**Comment by ssarrafan** [comment]
Checked with Emiley, Lee Ann and Shreyas and Shreyas said he can be the owner of DMP documentation. Assigning this master issue to @shreddd

**Comment by ssarrafan** [comment]
@shreddd what's the status of this? Is this in progress? Can you complete this by Friday?

**Comment by ssarrafan** [comment]
Discussed with Shreyas. We should check with @emileyfadrosh if we still need these pages or if there will be a new STREAMS documentation page?  Shreyas thinks we don't need these pages anymore.

**Comment by ssarrafan** [comment]
@emileyfadrosh said she will review these pages in a couple of weeks. I'm re-assigning to her and moving to the next sprint.

**Comment by shreddd** [comment]
Note that we have two copies as shown above, so if we want to keep these docs, it might be best to consolidate / drop one of these.

**Comment by ssarrafan** [comment]
@emileyfadrosh is it safe to assume that you've already updated https://microbiomedata.org/data-management/? 

For the readthedocs page let me know if you have any changes and I can do them in Github.

**Comment by ssarrafan** [comment]
@emileyfadrosh @shreddd let me know if you need help updating https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/data_plan.html or if you want this page removed.

Moving one more sprint.

**Comment by emileyfadrosh** [comment]
@eecavanna @ssarrafan I updated both website and created this PR: https://github.com/microbiomedata/NMDC_documentation/pull/76 -- I will close this ticket since I think I would consider this done :)
