### ISSUE TITLE
mg_annotation - Kaitlyn

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#5]
Follow the template below for the index.rst file that is in the docs folder of the repo for your workflow:
Title of Workflow
(Image)
Workflow overview
Workflow availability
Requirements for Execution
Hardware requirements
Workflow dependencies
Software
Database(s)
Sample dataset(s)
Input
Output
Version history
Point of contact

If you have updated figures please put the editable components of the figures [here](https://drive.google.com/drive/folders/1MEmTMLMPeDMQaF-LYnpJswjVmn9MUFTX) as well as in the documentation 
Please follow the following format for updating your documentation:

**Comment by kaijli** [comment]
WIP

**Comment by ssarrafan** [comment]
Thanks @kaijli do you expect this to be done next sprint?  Can you add a link to the draft here?

**Comment by ssarrafan** [comment]
@kaijli what's the status of this? Is this in progress? Can you complete this by Friday?
