### ISSUE TITLE
EnviroMS (NOM) - Yuri/Bea

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#51]
Follow the template below for the index.rst file that is in the docs folder of the repo for your workflow:
Title of Workflow
(Image)
Workflow overview
Workflow availability
Requirements for Execution
Hardware requirements
Workflow dependencies
Software
Database(s)
Sample dataset(s)
Input
Output
Version history
Point of contact

If you have updated figures please put the editable components of the figures [here](https://drive.google.com/drive/folders/1MEmTMLMPeDMQaF-LYnpJswjVmn9MUFTX) as well as in the documentation

@corilo @aclum please add additional components for this workflow documentation based on the meeting 12/3/24.

**Comment by ssarrafan** [comment]
@corilo @bmeluch @aclum any update on this?  Can this be done by the next sprint?

**Comment by ssarrafan** [comment]
> Yuri has been out all week but I can ask him on Monday.

Thank you @bmeluch! I'll move this issue to the next sprint with hope in my heart.  ;)

**Comment by corilo** [comment]
This was completed approximately two weeks ago, and we also finished a few other tasks from Alicia today. Is it possible that we're tracking this under a different issue? I seem to be having trouble locating it.

**Comment by aclum** [comment]
Yuri added the requested information about the calibration files to the index.rst and brought in changes @eecavanna had made to make sure the edit on github redirect works correctly. I consider this complete.
