### ISSUE TITLE
Web - Contact us page updates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#52]
Update [this web page](https://microbiomedata.org/contact/) so it's more user friendly 

- [x] Create hyperlinks
- [x] Add Bluesky

**Comment by ssarrafan** [comment]
@emileyfadrosh and @eecavanna who can make minor updates to the web pages?  Will Samantha be doing this?  
This is one I'm adding to the next sprint.

**Comment by ssarrafan** [comment]
Adding this issue for the next sprint to try to meet Jan deadline. If you prefer to have it in a later sprint let me know.

**Comment by emileyfadrosh** [comment]
I can't figure out how to add hyperlinks to the contacts list. @eecavanna maybe at some later date you could look into how to insert hyperlinks into the currently formatted "subtitle" section for each of the social media contacts?

**Comment by eecavanna** [comment]
I'll take a quick look now—to determine whether a theme change will be necessary. I'll report back in a couple minutes.

**Comment by eecavanna** [comment]
Update: This will require a theme change (by that, I mean, modifying the code of the WordPress theme we are using). I'll create a ticket for myself for next sprint.

**Comment by eecavanna** [comment]
Hi @emileyfadrosh, this functionality exists on the production website now.

In the "Contact" page editor, each item (i.e. logo/title/subtitle combo) has a new field named "URL" (shown here):

![image](https://github.com/user-attachments/assets/61667be5-6801-4e8c-af0c-0843760e1a60)

When that field is populated, the website will display that item as a link. When a visitor clicks on the item, they will be taken to the URL that was entered into that field.

Here are the links I expect to be entered into those URL fields:

- LinkedIn: `https://bit.ly/NMDC_LinkedIn`
- Bluesky: `https://bsky.app/profile/microbiomedata.org`
- Instagram: `https://www.instagram.com/microbiomedata/`
- Twitter/X: `https://x.com/microbiomedata`
- Contact our team directly: (see "Limitations" below)

#### Limitations

I just realized that the type of field I chose to use for that "URL" field restricts its values to being URLs; i.e., it does not allow values like `mailto:user@example.com`, which are used to make links that open up people's email clients with a new, initialized email.

<img width="1054" alt="image" src="https://github.com/user-attachments/assets/65a96b25-516f-4b85-aedd-96a78e15fc19" />

If you want to use a value like that (e.g. for the "Contact our team directly" item), you can let me know and I'll update the theme accordingly (I think it'll be a one-line change to the code). We may make another round of updates to the theme based upon the feedback people share during the website feedback session during today's NMDC sync—we could bundle in this "fix" into that round of updates (to minimize the number of times I request that PK deploy a new version of the theme, as I assume each request is a context switch for him).

**Comment by emileyfadrosh** [comment]
Done, looks fab!

**Comment by ssarrafan** [comment]
This really does look fabulous!  Is there any way to have the link work for the support email?

**Comment by emileyfadrosh** [comment]
I don't think so.... It needs a valid URL to have a link. 

![Screenshot 2024-12-19 at 3 31 18 PM](https://github.com/user-attachments/assets/76681f98-20ae-4d40-81e6-c1079dea3177)

**Comment by eecavanna** [comment]
I'll create a ticket in the (private) https://github.com/microbiomedata/nmdc-wordpress-theme/issues repository about not restricting the value to be a URL. I'll add it to next sprint's board.

**Comment by eecavanna** [comment]
Hi @emileyfadrosh, that input field can now contain `mailto:` links. I went ahead and updated the "Contact our team directly" item on the "Contact" page to have the link, `mailto:support@microbiomedata.org`. Now, when people click on it (and click "yes" on all the intermediate things their computer might show them), their email client will open up, showing an empty email that has `support@microbiomedata.org` in its "TO" field.

![Image](https://github.com/user-attachments/assets/7a3657a0-1721-4a1a-bc41-3a060d249793)
