### ISSUE TITLE
NMDC Overview updates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#53]
Please review and update the NMDC Overview and about our documentation
https://nmdc-documentation.readthedocs.io/en/latest/overview/nmdc_overview.html
https://nmdc-documentation.readthedocs.io/en/latest/overview/nmdc_overview.html#about-our-documentation

**Comment by ssarrafan** [comment]
Adding this issue for the next sprint to try to meet Jan deadline. If you prefer to have it in a later sprint let me know.

**Comment by ssarrafan** [comment]
@emileyfadrosh I'll move this one to the next sprint. Let me know if you need help updating this.  Instructions are at https://github.com/microbiomedata/docs?tab=readme-ov-file#maintenance

**Comment by emileyfadrosh** [comment]
I updated the text and created a PR for it here: https://github.com/microbiomedata/docs/pull/121

Closing this issue!
