### ISSUE TITLE
Workflows overview (reference)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#55]
Review and update the workflows overview documentation:
https://nmdc-workflow-documentation.readthedocs.io/en/latest/chapters/overview.html

**Comment by ssarrafan** [comment]
@aclum I'm assuming this is done no? Can we close this issue?

**Comment by aclum** [comment]
yes, updated text at https://docs.microbiomedata.org/workflows/chapters/overview.html
