### ISSUE TITLE
Update publications documentation

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#57]
Please review and update the publication docs pages on GH and on the website and make sure they are aligned (and do we need both?).

- [x] https://nmdc-documentation.readthedocs.io/en/latest/explanation/publications.html
- [x] https://microbiomedata.org/publications/

**Comment by emileyfadrosh** [comment]
hi @ssarrafan I updated the publications on the website earlier this week. However, I recommend removing the publications from the explanation section of the documentation. I don't think we need it! Let me know if you need more information, thanks.

**Comment by ssarrafan** [comment]
This was done last week. Closing issue.
