### ISSUE TITLE
meta mags - Kaitlyn

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#6]
Follow the template below for the index.rst file that is in the docs folder of the repo for your workflow:
Title of Workflow
(Image)
Workflow overview
Workflow availability
Requirements for Execution
Hardware requirements
Workflow dependencies
Software
Database(s)
Sample dataset(s)
Input
Output
Version history
Point of contact

If you have updated figures please put the editable components of the figures [here](https://drive.google.com/drive/folders/1MEmTMLMPeDMQaF-LYnpJswjVmn9MUFTX) as well as in the documentation 
Please follow the following format for updating your documentation:

**Comment by kaijli** [comment]
WIP

**Comment by kaijli** [comment]
This was updated recently by Chien-chi. Uploaded most recent version of figure.

**Comment by ssarrafan** [comment]
@kaijli can you add the link to the latest updates to this issue please? Can you close this by Friday?

**Comment by kaijli** [comment]
Documentation update in commit `[ff3af58dfe1420e06aa6e1c390d8f67b0c839785](https://github.com/microbiomedata/metaMAGs/commit/ff3af58dfe1420e06aa6e1c390d8f67b0c839785)`, figure changed in https://github.com/microbiomedata/metaMAGs/pull/60 (this repo is first guinea pig for new docs repo)
